//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeckoMouseEvents.APPrealService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kaysat-ps.org", ConfigurationName="APPrealService.ExchangeBLPortType")]
    public interface ExchangeBLPortType {
        
        // CODEGEN: Параметр "sData" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayItemAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kaysat-ps.org#ExchangeBL:SetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GeckoMouseEvents.APPrealService.SetDataResponse SetData(GeckoMouseEvents.APPrealService.SetDataRequest request);
        
        // CODEGEN: Параметр "sData" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayItemAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kaysat-ps.org#ExchangeBL:SetDataAmb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GeckoMouseEvents.APPrealService.SetDataAmbResponse SetDataAmb(GeckoMouseEvents.APPrealService.SetDataAmbRequest request);
        
        // CODEGEN: Параметр "sData" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayItemAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kaysat-ps.org#ExchangeBL:SetReferral", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GeckoMouseEvents.APPrealService.SetReferralResponse SetReferral(GeckoMouseEvents.APPrealService.SetReferralRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayItemAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kaysat-ps.org#ExchangeBL:GetReferral", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GeckoMouseEvents.APPrealService.GetReferralResponse GetReferral(GeckoMouseEvents.APPrealService.GetReferralRequest request);
        
        // CODEGEN: Параметр "sData" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayItemAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kaysat-ps.org#ExchangeBL:FinanceSource", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GeckoMouseEvents.APPrealService.FinanceSourceResponse FinanceSource(GeckoMouseEvents.APPrealService.FinanceSourceRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayItemAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kaysat-ps.org#ExchangeBL:GetRefferalByPerson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GeckoMouseEvents.APPrealService.GetRefferalByPersonResponse GetRefferalByPerson(GeckoMouseEvents.APPrealService.GetRefferalByPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kaysat-ps.org#ExchangeBL:GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GeckoMouseEvents.APPrealService.GetDataResult GetData(int size, string Token);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kaysat-ps.org")]
    public partial class ServiceElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ulong idField;
        
        private System.DateTime dateField;
        
        private ulong customerField;
        
        private ulong performerField;
        
        private long customerDepartamentField;
        
        private long performerDepartamentField;
        
        private System.Nullable<ulong> customerEmployeeField;
        
        private System.Nullable<ulong> performerEmployeeField;
        
        private long serviceIDField;
        
        private System.Nullable<ulong> patientIDField;
        
        private string patientFirstNameField;
        
        private string patientLastNameField;
        
        private string patientMiddleNameField;
        
        private System.Nullable<long> patientSexIDField;
        
        private string patientIDNField;
        
        private System.Nullable<System.DateTime> patientBirthDateField;
        
        private long financeSourceIDField;
        
        private System.Nullable<long> visitKindIDField;
        
        private System.Nullable<long> treatmentReasonIDField;
        
        private System.Nullable<decimal> costField;
        
        private decimal countField;
        
        private bool serviceKind2Field;
        
        private string leasingIDField;
        
        private string mKB10Field;
        
        private string doctorFirstNameField;
        
        private string doctorLastNameField;
        
        private string doctorMiddleNameField;
        
        private long serviceKindField;
        
        private long serviceCDSKindField;
        
        private sbyte paymentTypeField;
        
        private System.Nullable<System.DateTime> dateVerifiedField;
        
        private string resultField;
        
        private string serviceField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private bool deleteDateFieldSpecified;
        
        private string placeField;
        
        private System.Nullable<int> visit_typeField;
        
        private bool visit_typeFieldSpecified;
        
        private System.Nullable<int> group_idField;
        
        private bool group_idFieldSpecified;
        
        private string refferal_idField;
        
        private System.Nullable<ulong> parent_idField;
        
        private bool parent_idFieldSpecified;
        
        private System.Nullable<int> diag_typeField;
        
        private bool diag_typeFieldSpecified;
        
        private System.Nullable<ulong> mISField;
        
        private bool mISFieldSpecified;
        
        private System.Nullable<long> financeSourceOSMSField;
        
        private bool financeSourceOSMSFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ulong ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ulong Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("Customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ulong Performer {
            get {
                return this.performerField;
            }
            set {
                this.performerField = value;
                this.RaisePropertyChanged("Performer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long CustomerDepartament {
            get {
                return this.customerDepartamentField;
            }
            set {
                this.customerDepartamentField = value;
                this.RaisePropertyChanged("CustomerDepartament");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long PerformerDepartament {
            get {
                return this.performerDepartamentField;
            }
            set {
                this.performerDepartamentField = value;
                this.RaisePropertyChanged("PerformerDepartament");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<ulong> CustomerEmployee {
            get {
                return this.customerEmployeeField;
            }
            set {
                this.customerEmployeeField = value;
                this.RaisePropertyChanged("CustomerEmployee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<ulong> PerformerEmployee {
            get {
                return this.performerEmployeeField;
            }
            set {
                this.performerEmployeeField = value;
                this.RaisePropertyChanged("PerformerEmployee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long ServiceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
                this.RaisePropertyChanged("ServiceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<ulong> PatientID {
            get {
                return this.patientIDField;
            }
            set {
                this.patientIDField = value;
                this.RaisePropertyChanged("PatientID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string PatientFirstName {
            get {
                return this.patientFirstNameField;
            }
            set {
                this.patientFirstNameField = value;
                this.RaisePropertyChanged("PatientFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string PatientLastName {
            get {
                return this.patientLastNameField;
            }
            set {
                this.patientLastNameField = value;
                this.RaisePropertyChanged("PatientLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string PatientMiddleName {
            get {
                return this.patientMiddleNameField;
            }
            set {
                this.patientMiddleNameField = value;
                this.RaisePropertyChanged("PatientMiddleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<long> PatientSexID {
            get {
                return this.patientSexIDField;
            }
            set {
                this.patientSexIDField = value;
                this.RaisePropertyChanged("PatientSexID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string PatientIDN {
            get {
                return this.patientIDNField;
            }
            set {
                this.patientIDNField = value;
                this.RaisePropertyChanged("PatientIDN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<System.DateTime> PatientBirthDate {
            get {
                return this.patientBirthDateField;
            }
            set {
                this.patientBirthDateField = value;
                this.RaisePropertyChanged("PatientBirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public long FinanceSourceID {
            get {
                return this.financeSourceIDField;
            }
            set {
                this.financeSourceIDField = value;
                this.RaisePropertyChanged("FinanceSourceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<long> VisitKindID {
            get {
                return this.visitKindIDField;
            }
            set {
                this.visitKindIDField = value;
                this.RaisePropertyChanged("VisitKindID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<long> TreatmentReasonID {
            get {
                return this.treatmentReasonIDField;
            }
            set {
                this.treatmentReasonIDField = value;
                this.RaisePropertyChanged("TreatmentReasonID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<decimal> Cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
                this.RaisePropertyChanged("Cost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("Count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool ServiceKind2 {
            get {
                return this.serviceKind2Field;
            }
            set {
                this.serviceKind2Field = value;
                this.RaisePropertyChanged("ServiceKind2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string LeasingID {
            get {
                return this.leasingIDField;
            }
            set {
                this.leasingIDField = value;
                this.RaisePropertyChanged("LeasingID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string MKB10 {
            get {
                return this.mKB10Field;
            }
            set {
                this.mKB10Field = value;
                this.RaisePropertyChanged("MKB10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string DoctorFirstName {
            get {
                return this.doctorFirstNameField;
            }
            set {
                this.doctorFirstNameField = value;
                this.RaisePropertyChanged("DoctorFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string DoctorLastName {
            get {
                return this.doctorLastNameField;
            }
            set {
                this.doctorLastNameField = value;
                this.RaisePropertyChanged("DoctorLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string DoctorMiddleName {
            get {
                return this.doctorMiddleNameField;
            }
            set {
                this.doctorMiddleNameField = value;
                this.RaisePropertyChanged("DoctorMiddleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public long ServiceKind {
            get {
                return this.serviceKindField;
            }
            set {
                this.serviceKindField = value;
                this.RaisePropertyChanged("ServiceKind");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public long ServiceCDSKind {
            get {
                return this.serviceCDSKindField;
            }
            set {
                this.serviceCDSKindField = value;
                this.RaisePropertyChanged("ServiceCDSKind");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public sbyte PaymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
                this.RaisePropertyChanged("PaymentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public System.Nullable<System.DateTime> DateVerified {
            get {
                return this.dateVerifiedField;
            }
            set {
                this.dateVerifiedField = value;
                this.RaisePropertyChanged("DateVerified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("Service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
                this.RaisePropertyChanged("DeleteDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeleteDateSpecified {
            get {
                return this.deleteDateFieldSpecified;
            }
            set {
                this.deleteDateFieldSpecified = value;
                this.RaisePropertyChanged("DeleteDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public string Place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
                this.RaisePropertyChanged("Place");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public System.Nullable<int> Visit_type {
            get {
                return this.visit_typeField;
            }
            set {
                this.visit_typeField = value;
                this.RaisePropertyChanged("Visit_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Visit_typeSpecified {
            get {
                return this.visit_typeFieldSpecified;
            }
            set {
                this.visit_typeFieldSpecified = value;
                this.RaisePropertyChanged("Visit_typeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public System.Nullable<int> Group_id {
            get {
                return this.group_idField;
            }
            set {
                this.group_idField = value;
                this.RaisePropertyChanged("Group_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Group_idSpecified {
            get {
                return this.group_idFieldSpecified;
            }
            set {
                this.group_idFieldSpecified = value;
                this.RaisePropertyChanged("Group_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public string Refferal_id {
            get {
                return this.refferal_idField;
            }
            set {
                this.refferal_idField = value;
                this.RaisePropertyChanged("Refferal_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public System.Nullable<ulong> Parent_id {
            get {
                return this.parent_idField;
            }
            set {
                this.parent_idField = value;
                this.RaisePropertyChanged("Parent_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Parent_idSpecified {
            get {
                return this.parent_idFieldSpecified;
            }
            set {
                this.parent_idFieldSpecified = value;
                this.RaisePropertyChanged("Parent_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=39)]
        public System.Nullable<int> Diag_type {
            get {
                return this.diag_typeField;
            }
            set {
                this.diag_typeField = value;
                this.RaisePropertyChanged("Diag_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Diag_typeSpecified {
            get {
                return this.diag_typeFieldSpecified;
            }
            set {
                this.diag_typeFieldSpecified = value;
                this.RaisePropertyChanged("Diag_typeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=40)]
        public System.Nullable<ulong> MIS {
            get {
                return this.mISField;
            }
            set {
                this.mISField = value;
                this.RaisePropertyChanged("MIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MISSpecified {
            get {
                return this.mISFieldSpecified;
            }
            set {
                this.mISFieldSpecified = value;
                this.RaisePropertyChanged("MISSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=41)]
        public System.Nullable<long> FinanceSourceOSMS {
            get {
                return this.financeSourceOSMSField;
            }
            set {
                this.financeSourceOSMSField = value;
                this.RaisePropertyChanged("FinanceSourceOSMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FinanceSourceOSMSSpecified {
            get {
                return this.financeSourceOSMSFieldSpecified;
            }
            set {
                this.financeSourceOSMSFieldSpecified = value;
                this.RaisePropertyChanged("FinanceSourceOSMSSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kaysat-ps.org")]
    public partial class GetDataResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceElement[] servicesField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Services", Order=0)]
        public ServiceElement[] Services {
            get {
                return this.servicesField;
            }
            set {
                this.servicesField = value;
                this.RaisePropertyChanged("Services");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kaysat-ps.org")]
    public partial class FinanceElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private ulong person_idField;
        
        private System.DateTime direction_dateField;
        
        private string service_codeField;
        
        private int icd_typeField;
        
        private string ocd_codeField;
        
        private int direction_reasonField;
        
        private ulong sended_moField;
        
        private ulong sending_moField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ulong person_id {
            get {
                return this.person_idField;
            }
            set {
                this.person_idField = value;
                this.RaisePropertyChanged("person_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime direction_date {
            get {
                return this.direction_dateField;
            }
            set {
                this.direction_dateField = value;
                this.RaisePropertyChanged("direction_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string service_code {
            get {
                return this.service_codeField;
            }
            set {
                this.service_codeField = value;
                this.RaisePropertyChanged("service_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int icd_type {
            get {
                return this.icd_typeField;
            }
            set {
                this.icd_typeField = value;
                this.RaisePropertyChanged("icd_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ocd_code {
            get {
                return this.ocd_codeField;
            }
            set {
                this.ocd_codeField = value;
                this.RaisePropertyChanged("ocd_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int direction_reason {
            get {
                return this.direction_reasonField;
            }
            set {
                this.direction_reasonField = value;
                this.RaisePropertyChanged("direction_reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public ulong sended_mo {
            get {
                return this.sended_moField;
            }
            set {
                this.sended_moField = value;
                this.RaisePropertyChanged("sended_mo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public ulong sending_mo {
            get {
                return this.sending_moField;
            }
            set {
                this.sending_moField = value;
                this.RaisePropertyChanged("sending_mo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kaysat-ps.org")]
    public partial class ResultDirection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private bool statusField;
        
        private string infoField;
        
        private int errorCodeField;
        
        private System.Nullable<long> financeSourceIDField;
        
        private bool financeSourceIDFieldSpecified;
        
        private string iDEPSField;
        
        private System.Nullable<int> soc_statusField;
        
        private bool soc_statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("Info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<long> FinanceSourceID {
            get {
                return this.financeSourceIDField;
            }
            set {
                this.financeSourceIDField = value;
                this.RaisePropertyChanged("FinanceSourceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FinanceSourceIDSpecified {
            get {
                return this.financeSourceIDFieldSpecified;
            }
            set {
                this.financeSourceIDFieldSpecified = value;
                this.RaisePropertyChanged("FinanceSourceIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string IDEPS {
            get {
                return this.iDEPSField;
            }
            set {
                this.iDEPSField = value;
                this.RaisePropertyChanged("IDEPS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> soc_status {
            get {
                return this.soc_statusField;
            }
            set {
                this.soc_statusField = value;
                this.RaisePropertyChanged("soc_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool soc_statusSpecified {
            get {
                return this.soc_statusFieldSpecified;
            }
            set {
                this.soc_statusFieldSpecified = value;
                this.RaisePropertyChanged("soc_statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kaysat-ps.org")]
    public partial class DirectionResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private ResultDirection[] resultsDirectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ResultsDirection", Order=1)]
        public ResultDirection[] ResultsDirection {
            get {
                return this.resultsDirectionField;
            }
            set {
                this.resultsDirectionField = value;
                this.RaisePropertyChanged("ResultsDirection");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kaysat-ps.org")]
    public partial class DirectionElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private ulong person_idField;
        
        private System.DateTime direction_dateField;
        
        private ulong sending_mo_idField;
        
        private ulong personal_idField;
        
        private long position_idField;
        
        private ulong directed_mo_idField;
        
        private string service_codeField;
        
        private int finance_sourceField;
        
        private int icd_typeField;
        
        private string ocd_codeField;
        
        private int direction_reasonField;
        
        private System.Nullable<System.DateTime> cancel_dateField;
        
        private bool cancel_dateFieldSpecified;
        
        private System.Nullable<sbyte> paymentTypeField;
        
        private bool paymentTypeFieldSpecified;
        
        private System.Nullable<int> group_idField;
        
        private bool group_idFieldSpecified;
        
        private string patientIDNField;
        
        private string doctorFirstNameField;
        
        private string doctorLastNameField;
        
        private string doctorMiddleNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ulong person_id {
            get {
                return this.person_idField;
            }
            set {
                this.person_idField = value;
                this.RaisePropertyChanged("person_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime direction_date {
            get {
                return this.direction_dateField;
            }
            set {
                this.direction_dateField = value;
                this.RaisePropertyChanged("direction_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ulong sending_mo_id {
            get {
                return this.sending_mo_idField;
            }
            set {
                this.sending_mo_idField = value;
                this.RaisePropertyChanged("sending_mo_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ulong personal_id {
            get {
                return this.personal_idField;
            }
            set {
                this.personal_idField = value;
                this.RaisePropertyChanged("personal_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long position_id {
            get {
                return this.position_idField;
            }
            set {
                this.position_idField = value;
                this.RaisePropertyChanged("position_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public ulong directed_mo_id {
            get {
                return this.directed_mo_idField;
            }
            set {
                this.directed_mo_idField = value;
                this.RaisePropertyChanged("directed_mo_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string service_code {
            get {
                return this.service_codeField;
            }
            set {
                this.service_codeField = value;
                this.RaisePropertyChanged("service_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int finance_source {
            get {
                return this.finance_sourceField;
            }
            set {
                this.finance_sourceField = value;
                this.RaisePropertyChanged("finance_source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int icd_type {
            get {
                return this.icd_typeField;
            }
            set {
                this.icd_typeField = value;
                this.RaisePropertyChanged("icd_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ocd_code {
            get {
                return this.ocd_codeField;
            }
            set {
                this.ocd_codeField = value;
                this.RaisePropertyChanged("ocd_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int direction_reason {
            get {
                return this.direction_reasonField;
            }
            set {
                this.direction_reasonField = value;
                this.RaisePropertyChanged("direction_reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> cancel_date {
            get {
                return this.cancel_dateField;
            }
            set {
                this.cancel_dateField = value;
                this.RaisePropertyChanged("cancel_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cancel_dateSpecified {
            get {
                return this.cancel_dateFieldSpecified;
            }
            set {
                this.cancel_dateFieldSpecified = value;
                this.RaisePropertyChanged("cancel_dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<sbyte> paymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
                this.RaisePropertyChanged("paymentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentTypeSpecified {
            get {
                return this.paymentTypeFieldSpecified;
            }
            set {
                this.paymentTypeFieldSpecified = value;
                this.RaisePropertyChanged("paymentTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> group_id {
            get {
                return this.group_idField;
            }
            set {
                this.group_idField = value;
                this.RaisePropertyChanged("group_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool group_idSpecified {
            get {
                return this.group_idFieldSpecified;
            }
            set {
                this.group_idFieldSpecified = value;
                this.RaisePropertyChanged("group_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string PatientIDN {
            get {
                return this.patientIDNField;
            }
            set {
                this.patientIDNField = value;
                this.RaisePropertyChanged("PatientIDN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string DoctorFirstName {
            get {
                return this.doctorFirstNameField;
            }
            set {
                this.doctorFirstNameField = value;
                this.RaisePropertyChanged("DoctorFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string DoctorLastName {
            get {
                return this.doctorLastNameField;
            }
            set {
                this.doctorLastNameField = value;
                this.RaisePropertyChanged("DoctorLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string DoctorMiddleName {
            get {
                return this.doctorMiddleNameField;
            }
            set {
                this.doctorMiddleNameField = value;
                this.RaisePropertyChanged("DoctorMiddleName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kaysat-ps.org")]
    public partial class ServiceElementAmb : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ulong idField;
        
        private System.DateTime dateField;
        
        private ulong customerField;
        
        private long customerDepartamentField;
        
        private System.Nullable<ulong> customerEmployeeField;
        
        private System.Nullable<ulong> customerEmployeePostIDField;
        
        private string doctorFIOField;
        
        private System.Nullable<ulong> patientIDField;
        
        private string patientFIOField;
        
        private string patientIDNField;
        
        private System.Nullable<System.DateTime> patientBirthDateField;
        
        private string patientAddressField;
        
        private long visitKindIDField;
        
        private sbyte typeCallField;
        
        private string сallReasonField;
        
        private string noteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ulong ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ulong Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("Customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long CustomerDepartament {
            get {
                return this.customerDepartamentField;
            }
            set {
                this.customerDepartamentField = value;
                this.RaisePropertyChanged("CustomerDepartament");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<ulong> CustomerEmployee {
            get {
                return this.customerEmployeeField;
            }
            set {
                this.customerEmployeeField = value;
                this.RaisePropertyChanged("CustomerEmployee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<ulong> CustomerEmployeePostID {
            get {
                return this.customerEmployeePostIDField;
            }
            set {
                this.customerEmployeePostIDField = value;
                this.RaisePropertyChanged("CustomerEmployeePostID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string DoctorFIO {
            get {
                return this.doctorFIOField;
            }
            set {
                this.doctorFIOField = value;
                this.RaisePropertyChanged("DoctorFIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<ulong> PatientID {
            get {
                return this.patientIDField;
            }
            set {
                this.patientIDField = value;
                this.RaisePropertyChanged("PatientID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string PatientFIO {
            get {
                return this.patientFIOField;
            }
            set {
                this.patientFIOField = value;
                this.RaisePropertyChanged("PatientFIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string PatientIDN {
            get {
                return this.patientIDNField;
            }
            set {
                this.patientIDNField = value;
                this.RaisePropertyChanged("PatientIDN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<System.DateTime> PatientBirthDate {
            get {
                return this.patientBirthDateField;
            }
            set {
                this.patientBirthDateField = value;
                this.RaisePropertyChanged("PatientBirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string PatientAddress {
            get {
                return this.patientAddressField;
            }
            set {
                this.patientAddressField = value;
                this.RaisePropertyChanged("PatientAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public long VisitKindID {
            get {
                return this.visitKindIDField;
            }
            set {
                this.visitKindIDField = value;
                this.RaisePropertyChanged("VisitKindID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public sbyte TypeCall {
            get {
                return this.typeCallField;
            }
            set {
                this.typeCallField = value;
                this.RaisePropertyChanged("TypeCall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string СallReason {
            get {
                return this.сallReasonField;
            }
            set {
                this.сallReasonField = value;
                this.RaisePropertyChanged("СallReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kaysat-ps.org")]
    public partial class Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ulong idField;
        
        private bool statusField;
        
        private string infoField;
        
        private System.Nullable<long> financeSourceIDField;
        
        private bool financeSourceIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ulong ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("Info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<long> FinanceSourceID {
            get {
                return this.financeSourceIDField;
            }
            set {
                this.financeSourceIDField = value;
                this.RaisePropertyChanged("FinanceSourceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FinanceSourceIDSpecified {
            get {
                return this.financeSourceIDFieldSpecified;
            }
            set {
                this.financeSourceIDFieldSpecified = value;
                this.RaisePropertyChanged("FinanceSourceIDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kaysat-ps.org")]
    public partial class ServicesBatchResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ulong[] resultsField;
        
        private string messageField;
        
        private Result[] resultsMISField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Results", Order=0)]
        public ulong[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ResultsMIS", Order=2)]
        public Result[] ResultsMIS {
            get {
                return this.resultsMISField;
            }
            set {
                this.resultsMISField = value;
                this.RaisePropertyChanged("ResultsMIS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetData", WrapperNamespace="http://www.kaysat-ps.org", IsWrapped=true)]
    public partial class SetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Services", IsNullable=false)]
        public GeckoMouseEvents.APPrealService.ServiceElement[] sData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=1)]
        public string Token;
        
        public SetDataRequest() {
        }
        
        public SetDataRequest(GeckoMouseEvents.APPrealService.ServiceElement[] sData, string Token) {
            this.sData = sData;
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetDataResponse", WrapperNamespace="http://www.kaysat-ps.org", IsWrapped=true)]
    public partial class SetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=0)]
        public GeckoMouseEvents.APPrealService.ServicesBatchResult @return;
        
        public SetDataResponse() {
        }
        
        public SetDataResponse(GeckoMouseEvents.APPrealService.ServicesBatchResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetDataAmb", WrapperNamespace="http://www.kaysat-ps.org", IsWrapped=true)]
    public partial class SetDataAmbRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Services", IsNullable=false)]
        public GeckoMouseEvents.APPrealService.ServiceElementAmb[] sData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=1)]
        public string Token;
        
        public SetDataAmbRequest() {
        }
        
        public SetDataAmbRequest(GeckoMouseEvents.APPrealService.ServiceElementAmb[] sData, string Token) {
            this.sData = sData;
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetDataAmbResponse", WrapperNamespace="http://www.kaysat-ps.org", IsWrapped=true)]
    public partial class SetDataAmbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=0)]
        public GeckoMouseEvents.APPrealService.ServicesBatchResult @return;
        
        public SetDataAmbResponse() {
        }
        
        public SetDataAmbResponse(GeckoMouseEvents.APPrealService.ServicesBatchResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetReferral", WrapperNamespace="http://www.kaysat-ps.org", IsWrapped=true)]
    public partial class SetReferralRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Services", IsNullable=false)]
        public GeckoMouseEvents.APPrealService.DirectionElement[] sData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=1)]
        public string Token;
        
        public SetReferralRequest() {
        }
        
        public SetReferralRequest(GeckoMouseEvents.APPrealService.DirectionElement[] sData, string Token) {
            this.sData = sData;
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetReferralResponse", WrapperNamespace="http://www.kaysat-ps.org", IsWrapped=true)]
    public partial class SetReferralResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=0)]
        public GeckoMouseEvents.APPrealService.DirectionResults @return;
        
        public SetReferralResponse() {
        }
        
        public SetReferralResponse(GeckoMouseEvents.APPrealService.DirectionResults @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReferral", WrapperNamespace="http://www.kaysat-ps.org", IsWrapped=true)]
    public partial class GetReferralRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=0)]
        public ulong directed_mo_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=1)]
        public System.DateTime date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=2)]
        public string Token;
        
        public GetReferralRequest() {
        }
        
        public GetReferralRequest(ulong directed_mo_id, System.DateTime date, string Token) {
            this.directed_mo_id = directed_mo_id;
            this.date = date;
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReferralResponse", WrapperNamespace="http://www.kaysat-ps.org", IsWrapped=true)]
    public partial class GetReferralResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Services", IsNullable=false)]
        public GeckoMouseEvents.APPrealService.DirectionElement[] @return;
        
        public GetReferralResponse() {
        }
        
        public GetReferralResponse(GeckoMouseEvents.APPrealService.DirectionElement[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FinanceSource", WrapperNamespace="http://www.kaysat-ps.org", IsWrapped=true)]
    public partial class FinanceSourceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Services", IsNullable=false)]
        public GeckoMouseEvents.APPrealService.FinanceElement[] sData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=1)]
        public string Token;
        
        public FinanceSourceRequest() {
        }
        
        public FinanceSourceRequest(GeckoMouseEvents.APPrealService.FinanceElement[] sData, string Token) {
            this.sData = sData;
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FinanceSourceResponse", WrapperNamespace="http://www.kaysat-ps.org", IsWrapped=true)]
    public partial class FinanceSourceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=0)]
        public GeckoMouseEvents.APPrealService.DirectionResults @return;
        
        public FinanceSourceResponse() {
        }
        
        public FinanceSourceResponse(GeckoMouseEvents.APPrealService.DirectionResults @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRefferalByPerson", WrapperNamespace="http://www.kaysat-ps.org", IsWrapped=true)]
    public partial class GetRefferalByPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=0)]
        public string IIN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=1)]
        public string Token;
        
        public GetRefferalByPersonRequest() {
        }
        
        public GetRefferalByPersonRequest(string IIN, string Token) {
            this.IIN = IIN;
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRefferalByPersonResponse", WrapperNamespace="http://www.kaysat-ps.org", IsWrapped=true)]
    public partial class GetRefferalByPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kaysat-ps.org", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Services", IsNullable=false)]
        public GeckoMouseEvents.APPrealService.DirectionElement[] @return;
        
        public GetRefferalByPersonResponse() {
        }
        
        public GetRefferalByPersonResponse(GeckoMouseEvents.APPrealService.DirectionElement[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExchangeBLPortTypeChannel : GeckoMouseEvents.APPrealService.ExchangeBLPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExchangeBLPortTypeClient : System.ServiceModel.ClientBase<GeckoMouseEvents.APPrealService.ExchangeBLPortType>, GeckoMouseEvents.APPrealService.ExchangeBLPortType {
        
        public ExchangeBLPortTypeClient() {
        }
        
        public ExchangeBLPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExchangeBLPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExchangeBLPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExchangeBLPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeckoMouseEvents.APPrealService.SetDataResponse GeckoMouseEvents.APPrealService.ExchangeBLPortType.SetData(GeckoMouseEvents.APPrealService.SetDataRequest request) {
            return base.Channel.SetData(request);
        }
        
        public GeckoMouseEvents.APPrealService.ServicesBatchResult SetData(GeckoMouseEvents.APPrealService.ServiceElement[] sData, string Token) {
            GeckoMouseEvents.APPrealService.SetDataRequest inValue = new GeckoMouseEvents.APPrealService.SetDataRequest();
            inValue.sData = sData;
            inValue.Token = Token;
            GeckoMouseEvents.APPrealService.SetDataResponse retVal = ((GeckoMouseEvents.APPrealService.ExchangeBLPortType)(this)).SetData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeckoMouseEvents.APPrealService.SetDataAmbResponse GeckoMouseEvents.APPrealService.ExchangeBLPortType.SetDataAmb(GeckoMouseEvents.APPrealService.SetDataAmbRequest request) {
            return base.Channel.SetDataAmb(request);
        }
        
        public GeckoMouseEvents.APPrealService.ServicesBatchResult SetDataAmb(GeckoMouseEvents.APPrealService.ServiceElementAmb[] sData, string Token) {
            GeckoMouseEvents.APPrealService.SetDataAmbRequest inValue = new GeckoMouseEvents.APPrealService.SetDataAmbRequest();
            inValue.sData = sData;
            inValue.Token = Token;
            GeckoMouseEvents.APPrealService.SetDataAmbResponse retVal = ((GeckoMouseEvents.APPrealService.ExchangeBLPortType)(this)).SetDataAmb(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeckoMouseEvents.APPrealService.SetReferralResponse GeckoMouseEvents.APPrealService.ExchangeBLPortType.SetReferral(GeckoMouseEvents.APPrealService.SetReferralRequest request) {
            return base.Channel.SetReferral(request);
        }
        
        public GeckoMouseEvents.APPrealService.DirectionResults SetReferral(GeckoMouseEvents.APPrealService.DirectionElement[] sData, string Token) {
            GeckoMouseEvents.APPrealService.SetReferralRequest inValue = new GeckoMouseEvents.APPrealService.SetReferralRequest();
            inValue.sData = sData;
            inValue.Token = Token;
            GeckoMouseEvents.APPrealService.SetReferralResponse retVal = ((GeckoMouseEvents.APPrealService.ExchangeBLPortType)(this)).SetReferral(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeckoMouseEvents.APPrealService.GetReferralResponse GeckoMouseEvents.APPrealService.ExchangeBLPortType.GetReferral(GeckoMouseEvents.APPrealService.GetReferralRequest request) {
            return base.Channel.GetReferral(request);
        }
        
        public GeckoMouseEvents.APPrealService.DirectionElement[] GetReferral(ulong directed_mo_id, System.DateTime date, string Token) {
            GeckoMouseEvents.APPrealService.GetReferralRequest inValue = new GeckoMouseEvents.APPrealService.GetReferralRequest();
            inValue.directed_mo_id = directed_mo_id;
            inValue.date = date;
            inValue.Token = Token;
            GeckoMouseEvents.APPrealService.GetReferralResponse retVal = ((GeckoMouseEvents.APPrealService.ExchangeBLPortType)(this)).GetReferral(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeckoMouseEvents.APPrealService.FinanceSourceResponse GeckoMouseEvents.APPrealService.ExchangeBLPortType.FinanceSource(GeckoMouseEvents.APPrealService.FinanceSourceRequest request) {
            return base.Channel.FinanceSource(request);
        }
        
        public GeckoMouseEvents.APPrealService.DirectionResults FinanceSource(GeckoMouseEvents.APPrealService.FinanceElement[] sData, string Token) {
            GeckoMouseEvents.APPrealService.FinanceSourceRequest inValue = new GeckoMouseEvents.APPrealService.FinanceSourceRequest();
            inValue.sData = sData;
            inValue.Token = Token;
            GeckoMouseEvents.APPrealService.FinanceSourceResponse retVal = ((GeckoMouseEvents.APPrealService.ExchangeBLPortType)(this)).FinanceSource(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeckoMouseEvents.APPrealService.GetRefferalByPersonResponse GeckoMouseEvents.APPrealService.ExchangeBLPortType.GetRefferalByPerson(GeckoMouseEvents.APPrealService.GetRefferalByPersonRequest request) {
            return base.Channel.GetRefferalByPerson(request);
        }
        
        public GeckoMouseEvents.APPrealService.DirectionElement[] GetRefferalByPerson(string IIN, string Token) {
            GeckoMouseEvents.APPrealService.GetRefferalByPersonRequest inValue = new GeckoMouseEvents.APPrealService.GetRefferalByPersonRequest();
            inValue.IIN = IIN;
            inValue.Token = Token;
            GeckoMouseEvents.APPrealService.GetRefferalByPersonResponse retVal = ((GeckoMouseEvents.APPrealService.ExchangeBLPortType)(this)).GetRefferalByPerson(inValue);
            return retVal.@return;
        }
        
        public GeckoMouseEvents.APPrealService.GetDataResult GetData(int size, string Token) {
            return base.Channel.GetData(size, Token);
        }
    }
}
